version = 0.1

[default.deploy.parameters]
stack_name = "calculator-sam-stack"
resolve_s3 = false
s3_bucket = "calculator-sam-badal-ap-south-1"
s3_prefix = "calculator-sam-stack"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
